[app]
    mode  = "dev"
    name  = "ucenter"
    debug = true
[redis]
    host = "localhost"
    port = "6379"
    password = ""
    db = 0
[jwt]
    status = true
    secret = "zeDbBspcp2qy9032"
    skipper = []